version: '3.7'

services:

  postgres:
    image: postgres:12.8-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_SCHEMA=public
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
